package com.gaspay.ussdapp.model.enums;

public enum MenuLevel {
    START,
    UNREGISTERED_USER_INITIAL_REQUEST,
    INVALID_USER_SELECTION_RESPONSE,

    ENQUIRY,
    REGISTRATION,
    MAIN,

    PURCHASE,
    PURCHASE_REFILL,
    PURCHASE_RETURN,
    WALLET,
    ORDER_HISTORY,
    ACCOUNT,
    REPORT_INCIDENT
}
