package com.rancard.ussdapp.model.enums;

public enum MenuKey {
    UNREGISTERED_USER_INITIAL_RESPONSE,
    INVALID_USER_SELECTION_RESPONSE,
    MAIN_ENQUIRY_RESPONSE,
    ENQUIRY_REQUEST_CALLBACK_REQUEST_RESPONSE,
    ENQUIRY_REQUEST_CALLBACK_MSISDN_CONFIRMATION_RESPONSE,
    ENQUIRY_ALTERNATIVE_CALLBACK_NUMBER_RESPONSE,
    ENQUIRY_NO_CALLBACK_REQUEST_RESPONSE,
    ENQUIRY_END_ENQUIRY_RESPONSE_NO_CALLBACK,
    ENQUIRY_END_ENQUIRY_RESPONSE_CALLBACK,

    REGISTRATION_FIRST_NAME_RESPONSE,
    REGISTRATION_LAST_NAME_RESPONSE,
    REGISTRATION_ADDRESS_RESPONSE,
    REGISTRATION_ADDRESS_INVALID,
    REGISTRATION_CURRENT_FUEL_SOURCE_RESPONSE,
    REGISTRATION_FAMILY_SIZE_RESPONSE,

    REGISTRATION_SET_PIN_RESPONSE,
    REGISTRATION_PIN_INVALID,
    REGISTRATION_CONFIRM_PIN_RESPONSE,
    REGISTRATION_CONFIRM_PIN_INVALID,

    REGISTRATION_COMPLETE_RESPONSE,
    REGISTRATION_COMPLETE_NO_FOLLOW_RESPONSE,

    MAIN_MENU_RESPONSE,
    UNDER_CONSTRUCTION_RESPONSE,

    ORDER_HISTORY_FULL_ORDER_HISTORY_RESPONSE,


    TOPUP_AMOUNT_RESPONSE,
    TOPUP_AMOUNT_CONFIRMATION_RESPONSE,
    TOPUP_AWAITING_APPROVAL_RESPONSE,
    TOPUP_AMOUNT_INVALID,


    PURCHASE_MAIN_MENU_RESPONSE,
    PURCHASE_SIZE_OPTIONS_RESPONSE,
    PURCHASE_DIGITAL_ADDRESS_CONFIRM_OR_ENTER,
    PURCHASE_ORDER_CONFIRMATION_RESPONSE,
    PURCHASE_PAYMENT_METHOD,
    WALLET_PASSWORD_RESPONSE,
    MOMO_CHECK_AND_CONFIRM,

    MY_ACCOUNT_MAIN_MENU_RESPONSE,




}
