package com.rancard.ussdapp.model.enums;

public enum SubMenuLevel {

    /*UNREGISTERED USER*/
    MAIN_ENQUIRY,
    REQUEST_CALLBACK_QUESTION,
    REQUEST_CALLBACK_RESPONSE,
    CALLBACK_PHONE_NUMBER_CONFIRMATION,
    CALLBACK_PHONE_NUMBER_ENTRY,

    /*REGISTRATION*/
    REGISTRATION_FIRST_NAME,
    REGISTRATION_LAST_NAME,
    REGISTRATION_ADDRESS,
    REGISTRATION_CURRENT_FUEL_SOURCE,
    REGISTRATION_FAMILY_SIZE,
    REGISTRATION_SET_PIN,
    REGISTRATION_CONFIRM_PIN,
    REGISTRATION_COMPLETE,
    REGISTRATION_COMPLETE_MAIN_MENU_OR_EXIT,

    /*MAIN MENU*/
    MAIN,
    MAIN_MENU_RESPONSE,


    /*ORDER HISTORY*/
    VIEW_FULL_ORDER_HISTORY,
    FULL_ORDER_HISTORY_RESPONSE,
    VIEW_ORDER_HISTORY_BY_ID,

    /*WALLET*/
    WALLET_MAIN_MENU,
    TOPUP_AMOUNT,
    TOPUP_AMOUNT_CONFIRMATION,
    TOPUP_AMOUNT_CONFIRMATION_RESPONSE,


    /*PURCHASE*/
    PURCHASE_MAIN_MENU,
    PURCHASE_MAIN_MENU_RESPONSE,
    REFILL_MAIN_MENU,
    REFILL_DIGITAL_ADDRESS,
    REFILL_CONFIRM,
    REFILL_PAYMENT_WALLET,
    REFILL_PAYMENT_WALLET_RESPONSE

}
