package com.rancard.ussdapp.model.enums;

public enum SubMenuLevel {

    //ENQUIRY
    MAIN_ENQUIRY,
    REQUEST_CALLBACK_QUESTION,
    REQUEST_CALLBACK_RESPONSE,
    CALLBACK_PHONE_NUMBER_CONFIRMATION,
    CALLBACK_PHONE_NUMBER_ENTRY,

    REGISTRATION_FIRST_NAME,
    REGISTRATION_LAST_NAME,
    REGISTRATION_ADDRESS,
    REGISTRATION_CURRENT_FUEL_SOURCE,
    REGISTRATION_FAMILY_SIZE,
    REGISTRATION_COMPLETE,
    REGISTRATION_COMPLETE_MAIN_MENU_OR_EXIT,

    MAIN,
    MAIN_MENU_RESPONSE,
}
